### PR TITLE
Add explicit elasticsearch mappings for strings/ints/etc

### PR DESCRIPTION
**Pull request by erickt**
titan-es takes advantage of Elasticsearch's default behavior to automatically create indices new field. However, this  [functionality can be disabled](http://www.elasticsearch.org/guide/reference/api/index_/) by `index.mapper.dynamic: false` in `elasticsearch.yml`. Disabling this feature would then break Titan's ability to index various types. This pull request avoids that problem by explicitly creating field mappings for String/Float/Double/Byte/Short/Integer/Long/Boolean types. The before/after is demonstrated in this [gist](https://gist.github.com/erickt/6442316).

This also includes a patch to stop titan-es from fetching the stored fields from elasticsearch which should make doing an Elasticsearch query much more efficient when dealing with a large elasticsearch index.

Finally, it includes some other minor cleanup commits as well.

### CODE REVIEW

**Comment by mbroecheler** [comment]
Thanks for the pull request. I definitely did not consider @index.mapper.dynamic: false@.
I will take a look at your PR next week in connection with the other ES improvements.

**Comment by erickt** [comment]
This may not apply cleanly against the master branch. I intended to submit this PR against the 0.3 branch. I'll fix this by tomorrow.

**Comment by mbroecheler** [comment]
Sweet, thanks

On Wed, Sep 4, 2013 at 6:37 PM, Erick Tryzelaar notifications@github.comwrote:

> This may not apply cleanly against the master branch. I intended to submit
> this PR against the 0.3 branch. I'll fix this by tomorrow.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/pull/359#issuecomment-23838647
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbroecheler** [comment]
Manually merged the explicit mapping. https://github.com/thinkaurelius/titan/commit/cfecb0c85cf2539eb2bc01c90a83e7f3572d57d6

**Pull request closed without merging**
