### PR TITLE
make isLockingOptimistic a store feature

### PR DESCRIPTION
**Pull request by amcp**
addressed PR feedback on adding isLockingOptimistic to store features

### CODE REVIEW

**Comment by amcp** [comment]
I removed all the unrelated changes in this new PR and made the changes you suggested. Any updates?

**Comment by ghost** [comment]
Is there a need to update Chapter 12 of the documents to explain how this is defaulted and configured now ?

**Comment by amcp** [comment]
There may be. I will investigate.

**Comment by amcp** [comment]
this is synced off an old branch. will create a new PR off titan11.

**Pull request closed without merging**
