### PR TITLE
Fix for gremlin.sh will take more than 9 params https://github.com/thinkaurelius/titan/issues/510

### PR DESCRIPTION
**Pull request by tsecheran**
Fix for the issue https://github.com/thinkaurelius/titan/issues/510, please review this and accept the patch.

### CODE REVIEW

**Comment by dalaro** [comment]
Looks good to me.  Gave it a quick test:

``` bash
$ cat test.groovy 
for (a in args) {
    println(a)
}
$ bin/gremlin.sh -e test.groovy `seq 0 20`
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
$ bin/gremlin.sh -e test.groovy "a b" "c"
a b
c
```

**Comment by spmallette** [comment]
Should this change be replicated in Gremlin?

**Comment by dalaro** [comment]
I think so. `${var}` is ancient syntax.  Since gremlin.sh already uses the relatively new `$(command)` substitution syntax, it must be safe to use `${var}`.

**Comment by spmallette** [comment]
Just pushed the same change over in gremlin.  As Titan moves to support TinkerPop 2.5.0, we need to convert the Titan custom Gremlin REPL to a "plugin" for Gremlin.  Then we don't need to maintain this code in two places anymore.  cc/ @mbroecheler

**Comment by mbroecheler** [comment]
Stephen, can you take care of this aspect for the 0.5 release of Titan?

On Thu, Dec 19, 2013 at 6:24 AM, stephen mallette
notifications@github.comwrote:

> Just pushed the same change over in gremlin. As Titan moves to support
> TinkerPop 2.5.0, we need to convert the Titan custom Gremlin REPL to a
> "plugin" for Gremlin. Then we don't need to maintain this code in two
> places anymore. cc/ @mbroecheler https://github.com/mbroecheler
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/pull/513#issuecomment-30931836
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by spmallette** [comment]
sure...by "we" i basically meant "me"

**Comment by mbroecheler** [comment]
Ah, the royal "we" - got it ;-)

On Thu, Dec 19, 2013 at 4:05 PM, stephen mallette
notifications@github.comwrote:

> sure...by "we" i basically meant "me"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/pull/513#issuecomment-30978847
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Pull request merged**
