### PR TITLE
Preconditions causes JSON serialization errors with Gremlin Server

### PR DESCRIPTION
**Pull request by pluradj**
https://github.com/thinkaurelius/titan/issues/1089

With this fix, the example in the issue succeeds with this JSON result

```
{"requestId":"e905ec1c-7a30-44a3-93c8-fb6a17901349","status":{"message":"","code":200,"attributes":{}},"result":{"data":[{"id":{"outVertexId":4272,"typeId":1029,"relationId":1046,"inVertexId":0,"longRepresentation":[1046,4272,1029]},"value":"jason","label":"name"},{"id":{"outVertexId":8368,"typeId":1029,"relationId":2070,"inVertexId":0,"longRepresentation":[2070,8368,1029]},"value":"david","label":"name"}],"meta":{}}}
```

### CODE REVIEW

**Comment by spmallette** [comment]
@pluradj thanks for researching out the cause of #1089.  While your fix here in Titan does correct the bad behavior, i think that there was a better solution more common to all vendor implementations on the TinkerPop side.  You can see my fix here in this commit if you are interested:

https://github.com/apache/incubator-tinkerpop/commit/d1f5f8603c60f584b7a514280980d3957e451e69

Basically, I'd left a hole open in the serialization process that allowed the custom serializer of Titan to be bypassed when types were not embedded.  You can see the result of my fix here:

``` json
{"id":"17e-3bk-2dh","value":"marko","label":"name"}
```

Note the more compact serialization of the id field now that the jackson default serialization is no longer slipping through.

**Comment by pluradj** [comment]
Nice fix, thanks Stephen.

**Comment by pluradj** [comment]
I just tested it out... Titan is still throwing an IllegalStateException because of the Preconditions.

```
[WARN] JsonMessageSerializerV1d0 - Response [ResponseMessage{requestId=03599f05-12fc-e89b-e81c-01f0b6877a18, status=ResponseStatus{code=SUCCESS, message='', attributes={}}, result=ResponseResult{data=[vp[name->david], vp[name->jason]], meta={}}}] could not be serialized by org.apache.tinkerpop.gremlin.driver.ser.AbstractJsonMessageSerializerV1d0.
[WARN] WsGremlinResponseEncoder - The result [ResponseResult{data=[vp[name->david], vp[name->jason]], meta={}}] in the request 03599f05-12fc-e89b-e81c-01f0b6877a18 could not be serialized and returned.
org.apache.tinkerpop.gremlin.driver.ser.SerializationException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.IllegalStateException) (through reference chain: java.util.ArrayList[0]->com.thinkaurelius.titan.graphdb.relations.RelationIdentifier["inVertexId"])
    at org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerV1d0.serializeResponseAsString(JsonMessageSerializerV1d0.java:100)
    at org.apache.tinkerpop.gremlin.server.handler.WsGremlinResponseEncoder.encode(WsGremlinResponseEncoder.java:79)
    at org.apache.tinkerpop.gremlin.server.handler.WsGremlinResponseEncoder.encode(WsGremlinResponseEncoder.java:45)
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
    at org.apache.tinkerpop.gremlin.server.handler.IteratorHandler.write(IteratorHandler.java:119)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
    at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.IllegalStateException) (through reference chain: java.util.ArrayList[0]->com.thinkaurelius.titan.graphdb.relations.RelationIdentifier["inVertexId"])
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
    at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:190)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:674)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil.writeWithType(GraphSONUtil.java:46)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers.serializerVertexProperty(GraphSONSerializers.java:333)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers.access$000(GraphSONSerializers.java:55)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers$VertexPropertyJacksonSerializer.serialize(GraphSONSerializers.java:68)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers$VertexPropertyJacksonSerializer.serialize(GraphSONSerializers.java:56)
    at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:113)
    at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:73)
    at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:19)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil.writeWithType(GraphSONUtil.java:46)
    at org.apache.tinkerpop.gremlin.driver.ser.AbstractJsonMessageSerializerV1d0$ResponseMessageSerializer.ser(AbstractJsonMessageSerializerV1d0.java:235)
    at org.apache.tinkerpop.gremlin.driver.ser.AbstractJsonMessageSerializerV1d0$ResponseMessageSerializer.serialize(AbstractJsonMessageSerializerV1d0.java:205)
    at org.apache.tinkerpop.gremlin.driver.ser.AbstractJsonMessageSerializerV1d0$ResponseMessageSerializer.serialize(AbstractJsonMessageSerializerV1d0.java:197)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
    at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3385)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2779)
    at org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerV1d0.serializeResponseAsString(JsonMessageSerializerV1d0.java:97)
    ... 16 more
Caused by: java.lang.IllegalStateException
    at com.google.common.base.Preconditions.checkState(Preconditions.java:134)
    at com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.getInVertexId(RelationIdentifier.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:536)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:666)
    ... 33 more

```

**Comment by spmallette** [comment]
ok - i didn't publish a fresh TinkerPop SNAPSHOT.  You have this problem after rebuilding TinkerPop3 and Titan all locally?

**Comment by pluradj** [comment]
Yes, I built TP3 master and Titan titan09 locally. The stack trace is showing org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil.writeWithType(GraphSONUtil.java:46) so that is the new code that you just put in.

I applied the Preconditions fix from before, and the resulting JSON doesn't seem to use Titan's custom serializers.

**Comment by spmallette** [comment]
ugh - ok - must have missed something - let me dig in again.  sorry....

**Comment by spmallette** [comment]
try this - in your `gremlin-server.yaml` do add this:

``` yaml
- { className: org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerV1d0, config: { useMapperFromGraph: graph }}
```

basically, you need to tell the serializer to use the custom serializers from the graph you have configured in the yaml file (in your case the Titan instance is named "graph").  Hopefully that helps.  I don't have good docs around this - will work on that now.  When you confirm that this fixes your problem i'll close this out.

**Comment by pluradj** [comment]
Thanks, Stephen! So this is interesting... it works great in my http/rest YAML

``` yaml
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerGremlinV1d0 }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerV1d0, config: { useMapperFromGraph: graph } }
```

but my ws YAML is still failing with same stack trace as before.

``` yaml
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0 }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerGremlinV1d0 }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerV1d0, config: { useMapperFromGraph: graph } }
```

**Comment by spmallette** [comment]
that's really strange.  your mime type with websockets is "application/json" i assume.  if so, your config should work.  for fun, perhaps you should add the same setting to: `JsonMessageSerializerGremlinV1d0` and see if that helps.

let me look into it some more.

**Comment by spmallette** [comment]
actually, if you are only using `application/json` (or not specifying a mime type) perhaps you should just remove the other serializers aside from:

``` yaml
 - { className: org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerV1d0, config: { useMapperFromGraph: graph } }
```

wonder if it is grabbing the wrong one somehow?

**Comment by pluradj** [comment]
I tried it with just a single serializer defined, but same error.
Seems like in the ws case, it has a BeanSerializer instead of the TitanGraphSONModule$RelationIdentifierSerializer.

**Pull request closed without merging**
