### PR TITLE
#670

### LINKED ISSUE #670: titan05-M1 ElasticSearch mutate Bug
``` Java
if (mutation.hasDeletions()) {
                        if (mutation.isDeleted()) {
                            log.trace("Deleting entire document {}", docid);
                            brb.add(new DeleteRequest(indexName, storename, docid));
                            bulkrequests++;
                        } else {
                            StringBuilder script = new StringBuilder();
                            for (String key : Iterables.transform(mutation.getDeletions(),IndexMutation.ENTRY2FIELD_FCT)) {
                                script.append("ctx._source.remove(\"" + key + "\"); ");
                                log.trace("Deleting individual field [{}] for document {}", key, docid);
                            }
                            brb.add(client.prepareUpdate(indexName, storename, docid).setScript(script.toString()));
                        }
                    }
                    if (mutation.hasAdditions()) {
                        if (mutation.isNew()) { //Index
                            log.trace("Adding entire document {}", docid);
                            brb.add(new IndexRequest(indexName, storename, docid).source(getContent(mutation.getAdditions())));
                            bulkrequests++;
                        } else {
                            boolean needUpsert = !mutation.hasDeletions();
                            XContentBuilder builder = getContent(mutation.getAdditions());
                            UpdateRequestBuilder update = client.prepareUpdate(indexName, storename, docid).setDoc(builder);
                            if (needUpsert) update.setUpsert(builder);
                            log.trace("Updating document {} with upsert {}", docid, needUpsert);
                            brb.add(update);
                        }
                    }

when brb add an item,bulkrequests must plus one,otherwise sometimes the index mutate can't excute
```

### PR DESCRIPTION
**Pull request by boliza**
fixed #670

### CODE REVIEW

**Comment by dalaro** [comment]
This looks right to me... doing `brb.add` without incrementing `bulkrequests` seems like a bug, based on the context in ESIndex.java

@mbroecheler does this look good to you also?

**Comment by dalaro** [comment]
Assuming the patch looks correct, we could also just pull the `bulkrequests` increment up one level in those nested if-blocks.

**Comment by mbroecheler** [comment]
great catch, thanks @boliza. And yes, we can move the increment up.

**Comment by mbroecheler** [comment]
@dalaro also, we should investigate why our unit test coverage did not catch this

**Comment by dalaro** [comment]
You're right, I'll try adding a failing unit test and then merging #670 and pulling up the increment.

**Pull request merged**
