### PR TITLE
Changed APIs and pom to HBase 0.96-hadoop2. Breaks compability with 0.94...

### PR DESCRIPTION
**Pull request by ghost**
Regarding issue #526.

### CODE REVIEW

**Comment by ghost** [comment]
Regarding issue #526.

Omitted the row size in the Delete call in order to handle the deletion issues with the previous pull request.

Tested and verified that it now successfully adds and deletes edges and vertices up until HBase 0.96.1.1.

**Comment by dalaro** [comment]
Thanks for putting this together.

You're right to fix up that Delete call.  I want to remove all the deprecated calls from the storage adapter at some point.

We're not ready to break Hadoop 1 and HBase 0.94 compatibility yet, so I think we'll have to implement this differently.

I have a specific question about HDP vs Apache client artifacts.  Does Titan need to use the HBase and Hadoop artifacts hosted in Hortonworks's repo @ http://repo.hortonworks.com/content/repositories/releases/org/apache/ to be compatible with HDP2 clusters, or do Apache client artifacts of similar versions work just as well when talking to HDP services?

**Comment by dalaro** [comment]
I'm refactoring the titan-hbase module into separate 0.96 and 0.94 builds.  The vast majority of the code and all of the tests still reside in a single set of files in titan-hbase/src.  I moved the one 0.94 <-> 0.96 source incompatibility, Compression.Algorithm moving between packages, into a little helper class which is defined separately for each build.

The default for 0.96 is to build against 0.96.1.1-hadoop2 with the default Hadoop version (2.2.0). 

I'm probably going to tweak this some more, but the changes I just described are in titan05 now.  I like this approach because it lets us keep compatibility with multiple HBase + Hadoop stack versions.

**Comment by ghost** [comment]
This is great news. 

Re compability between HDP2 and the Apache artifacts, I've been using the Apache ones with titan05 in my sandbox. I know they have some special versions in there, but it's been working quite well for me at least. Probably someone from Hortonworks can answer that definitively.

**Comment by dalaro** [comment]
I think the changes from this PR have all made it into titan05 in slightly different forms.  The Delete constructor call got refactored out of existence as part of configurable timestamp support in f0d41c6743a3514966326d90e9b1234c5d58e16e.  Hadoop 2.x / HBase 0.96 modules and Maven profiles are also in titan05.

So I'm closing this, but please reopen if I missed something.

**Pull request closed without merging**
