### PR TITLE
Added support for Rexster 2.4.0 Metrics

### PR DESCRIPTION
**Pull request by zachkinstner**
This updates Titan to use TinkerPop 2.4.0-SNAPSHOT.  

Support for Metrics in Titan is dependent upon these changes in Rexster 2.4.0: https://github.com/tinkerpop/rexster/pull/307

I was able to get the metrics to work by making `ReporterConfig` setup occur first -- I had to move `RexProRexsterServer` and `HttpRexsterServer` instantiation out of the `RextsterTitanServer` constructor and into the `start` method instead.  It seems to work fine, and I suppose it shouldn't cause an issue as long as `start` is only called once.

There was one issue in `TitanSpecificBlueprintsTestSuite` that I didn't know how to fix. This particular test should fail every time.

More discussion about Titan Metrics: https://github.com/thinkaurelius/titan/issues/268

### CODE REVIEW

**Comment by dalaro** [comment]
Thanks!

Can you help me understand your changes to RexsterTitanServer?  I think you mentioned that these changes were necessary in #268.  I seem to have nearly identical changes already locally committed except for your RexsterTitanServer stuff (and the eclipse ignores).

Sorry about the duplicated work.  I postponed pushing until resolving a test failure in Titan-BDB that appeared with Blueprints 2.4.0-SNAPSHOT, but I think that's now fixed with https://github.com/tinkerpop/blueprints/pull/402.

I fixed (?) TitanSpecificBlueprintsTestSuite by just passing the String "friend" as the final argument to addEdge.  At least, I think I fixed it because the test passes this way.

**Comment by zachkinstner** [comment]
> Sorry about the duplicated work.

No worries -- I'm just trying to help out where I can.

> Can you help me understand your changes to RexsterTitanServer?

Sure. The diff makes it hard to see what's happening.  I found that placing `ReporterConfig` setup first (before the server objects were created) made things work for me. However, `ReporterConfig` needs a `RexsterApplication` parameter, which in turn needs the graph object. The graph object is created in the `start()` method.

So, to get everything into the correct order, I had to move `RexProRexsterServer` and `HttpRexsterServer` creation out of the constructor, and into the `start()` method.  It's completely possible there are better ways to do this, but I just stopped once I had it working.

**Comment by dalaro** [comment]
Thanks.  I looks OK to me, though I don't have a deep understanding of what's going on here.  Do you think calling `reporterConfig.enable()` before creating server objects is the key point?

I cherry-picked just your changes on RexsterTitanServer and I'm running tests locally now.  Should be pushed shortly...

**Comment by dalaro** [comment]
Pushed RexsterTitanServer changes in f09aa4d82745a7831ba84afcafc7dc53d6671bb3 and slightly different and more restrictive Eclipse .gitignore changes in b68ff656a16d69f315eea8bc3d7cbcf960598e74.  What Eclipse version/feature produces *.prefs?

**Comment by zachkinstner** [comment]
> Do you think calling `reporterConfig.enable()` before creating server objects is the key point?

Yes, I think so.  Practically speaking, I'm not sure that it matters -- the various parameter and logical dependencies surrounding the `reporterConfig.enable()` call are forcing the order of setup/creation.

> What Eclipse version/feature produces *.prefs?

Not sure, entirely... I've only been working with Java for the past few weeks.  I'm using "Eclipse IDE for Java Developers, Version: Juno Service Release 2" with the Maven plugin installed.

**Comment by spmallette** [comment]
Given the version at which you guys are working, calling `enable()` is important as the reporters are not started in the individual `RexsterServer` implementations.  I'd expect some more change around this feature given some work i'm currently doing in a branch...you likely shouldn't have to call `enable()` anymore once we have a stable release of 2.4.0.

**Comment by dalaro** [comment]
Thanks, @spmallette.

I think the contents of this request have been completely merged into titan03, so I'm closing it.  Please do open another request if I've missed something.

**Pull request closed without merging**
