### PR TITLE
Add UUID support

### PR DESCRIPTION
**Pull request by BrynCooke**
https://github.com/thinkaurelius/titan/issues/887
This request adds a UUID serializer.
Strings and Java UUID objects are supported allowing roundtrip via GSON.
Internally UUIDs are stored as two longs.

### CODE REVIEW

**Comment by mikedias** [comment]
Hi @BrynCooke, 

This PR should consider the data type register in ElasticSearchIndex, isn't it?

**Comment by BrynCooke** [comment]
@dalaro Should I add mixed index support at the same time? I don't think this will be too difficult.

**Comment by mbroecheler** [comment]
@BrynCooke Sure, why not ;-)

**Comment by boliza** [comment]
@BrynCooke so also fix #769 :)

**Pull request merged**
