### PR TITLE
must contains 0.4.2

### PR DESCRIPTION
**Pull request by boliza**
if not contains 0.4.2,can't open the titan instance which is create by titan 0.4.2

### CODE REVIEW

**Comment by dalaro** [comment]
Whoops.  This is severe.  Work on it now.

**Comment by boliza** [comment]
could I redownload to fixed it?

**Comment by dalaro** [comment]
I built Titan 0.4.4 zipfiles that are compatible with 0.4.2 and 0.4.3:

https://github.com/thinkaurelius/titan/wiki/Downloads#titan-044

Artifacts are forthcoming to Maven Central later today (they aren't synced yet).

**Comment by boliza** [comment]
thanks for your work

**Pull request closed without merging**
