### PR TITLE
id: 1278 Pin guava version to 18

### PR DESCRIPTION
**Pull request by fcalderonnearsoft**
desc: added <version>18.0</version> to pom.xml
 reviewer: sayrer

### CODE REVIEW

**Comment by fcalderonnearsoft** [comment]
@spmallette @dalaro is there any chance that someone could check this, please?

**Comment by spmallette** [comment]
ha - that's going to have to be a @dalaro job. did you run the full test suite successfully?

**Comment by fcalderonnearsoft** [comment]
@spmallette Yes, I did! :)

**Comment by okram** [comment]
We shouldn't "pin" anything. There will always be version differences between different users. Instead either Titan uses shading or the user shades their jars.

**Comment by spmallette** [comment]
yeah - looks like @dalaro had shading in mind: #1139

**Comment by fcalderonnearsoft** [comment]
@spmallette @okram What do you mean with 'shading' ?

**Comment by spmallette** [comment]
It basically would repackage guava for a particular version under the titan distribution. You can see how it's done here in TinkerPop for `gremlin-shaded`:

https://github.com/apache/incubator-tinkerpop/blob/49ed3612c54c4e056796d654c24de6bb9496e775/gremlin-shaded/pom.xml

Looking at that, you can see that we repackaged kryo, for example, with a `org.apache.tinkerpop.shaded.kryo` package name. That's at least one use case of shading anyway.  You should probably read up on the Maven shade plugin to learn more.

**Pull request closed without merging**
