### PR TITLE
Added support for different cardinality indexing in ES.

### PR DESCRIPTION
**Pull request by BrynCooke**
https://github.com/thinkaurelius/titan/issues/593
ES mutations are now done by script except if it is a new document.
Tests added.
Index.supports is called upon index creation to check if the key information supported. This results in a better error message.

@dalaro Please can you review the code changes.

### CODE REVIEW

**Comment by BrynCooke** [comment]
@dalaro Hold on. The upgrade to ES1.5 has broken this.
Apparently script updates are now different.

**Comment by BrynCooke** [comment]
I think this is to do with scripting being disabled:
http://www.elastic.co/guide/en/elasticsearch/reference/1.x/modules-scripting.html

**Comment by dalaro** [comment]
Last time I looked at this (#736), I wasn't convinced that dynamic scripting was actually a hard requirement.  Perhaps we could rework field deletion to avoid it.

**Comment by BrynCooke** [comment]
@dalaro I think this is good to go (After merging with the titan09 branch).

Dynamic scripting is already a requirement for Titan so to removing it should be pulled in to a different issue. It can probably be done, but would deployment of script files to every ES node in the cluster. I think we should wait for people to ask for this.

I think that the script language has either changed or the detection has changed from the earlier version of ES. It just so happened that the previous scripts were valid groovy and javascript.

Secondly there are race conditions in the tests. Particularly ElasticSearchConfigTest but anywhere where we embed ES could be affected.

As far as I can tell programmatically starting and stopping a node is not a synchronous operation, and examining the log files for started and stopped markers is insufficient to prevent conditions where:
1. An ES node is queried before it is ready.
2. An ES node joins a cluster that has been shut down.

This manifests itself in failed queries, data from previous tests replicating to new tests, nodes failing to start up due to the 'old master' node shutting down.

I have tried to make this better by pulling out the nodes in to separate clusters for each test and adding a delay after ES has started, but occasionally the tests still fail.

**Pull request merged**
