### PR TITLE
Add prefix querying to Lucene and Elasticsearch backends and regexp querying to Elasticsearch backend.

### PR DESCRIPTION
**Pull request by jkschneider**
Used already to list all of the artifacts in an Ivy repository represented in Titan that have names that begin with "comm".  This is being used on a web front end to link a textbox autocompletion mechanism to a specific property on vertices in a Titan graph.

image

### CODE REVIEW

**Comment by ghost** [comment]
What is the status of getting these changes merged into the master branch? It appears that the merge is blocked by a build failure. I am intersted in adding another ES/Lucene feature, fuzzy search. I would like to start with the code base that includes these changes.

**Comment by jkschneider** [comment]
Sorry about the typo there originally.  The code for this feature compiles and tests successfully.  The overall Travis-CI build is failing due an unrelated "java.lang.ClassNotFoundException: java.nio.channels.SeekableByteChannel"

**Comment by erickt** [comment]
@jkschneider: this looks pretty good, and I was thinking about adding this support myself. However, I noticed you ended up re-indenting some of the code. Would you be able to fix it?

**Comment by jkschneider** [comment]
@erickt: Thanks for taking a look.  I changed the tabs to spaces.

**Comment by mbroecheler** [comment]
Thanks for the PR. This is a really useful feature. We are getting close to the 0.4.0 release and next week is our "Improving Indexing and ElasticSearch" week. I will review the code then and merge it in.
Thanks again.

**Comment by mbroecheler** [comment]
Manually merged the RexEx feature into Titan.
https://github.com/thinkaurelius/titan/commit/cfecb0c85cf2539eb2bc01c90a83e7f3572d57d6

**Pull request closed without merging**
