### PR TITLE
TITAN 1126: upgrade to latest solr and improve solrcloud support

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/thinkaurelius/titan/issues/1126

Adds a new property and additional support for SolrCloud to allow re-use of config sets and reduce amount of manual configuration needed to use Titan with Solr.

### CODE REVIEW

**Comment by dalaro** [comment]
This looks interesting.  I like the documentation changes.  If I'm reading the source changes right, this affects creation of new Solr-backed indices.  It introduces a new config option called `configset`.  If set, Titan will assume it names a extant directory containing config files in the Solr cluster, and Titan will setup collections it creates to reuse those config files.  Critically, it does not touch the actual name of the collection, just the name of a collection's configs.  So we can still have multiple indices per backend, but now the user has the option of writing and uploading Solr config files once and then reusing them across multiple collections.

Did I understand the PR?  If so, do you have any suggestions on how we should test this?

**Comment by dalaro** [comment]
Also: can you please sign the new Titan CLA (http://titan-cla.datastax.com/)?

**Comment by ghost** [comment]
You summarized the pull request/changes precisely.

One detail: Once the initial config set is loaded from disk into Zookeeper
by SolrCloud, future references to the config set are reused from Zookeeper
and not from disk.

**Comment by ghost** [comment]
Dan,

You asked about verification.

I am thinking out loud with you here rather than proposing anything
specific at the moment.

The way I verify this feature manually is to create several mixed indexes
in a test Titan
database, and make sure the indexes are working as expected via the Gremlin
shell.

I then log into the Zookeeper cli - zkCli.sh and verify that the Solr Cloud
data there is as I would expect to see it.

Under /configs I expect to see only a single configset defined - the one
referenced in the Titan configuration file and the one copied under solr
cloud.  There should be no other config sets present :    ls /configs

Contrast this to the default behavior where multiple configsets will appear
in the ls /configs listing.

I manually check the collections in Zookeeper:  ls /collections to make
sure there is an entry for all of the indexes that were created in Titan.

I manually verify that there is only a single directory under the Solr
Cloud directory structure that contains the single Titan default config set
(or whatever config set I am re-using).  Contrast this to the default
behavior where multiple manual copies and subdirectories for each config
set are required.

That's about it.  What do you think ?

**Comment by dalaro** [comment]
Thanks for replying about testing.  Accessing ZK is an interesting angle.  I wonder if there is an programmatically-accessible API that easily dumps enough config information for test assertions (maybe that's ZK in this case).  That's sort of how we test some config-manipulating options in ES.

This is a substantial quality of life improvement without, as far as I can tell, much of a potential surface area for bugs; and the fallback to pre-merge behavior in the default configuration is another plus.  I merged it into titan09.

**Pull request merged**
