### PR TITLE
porting titan-persistit to 0.3.x

### PR DESCRIPTION
**Pull request by bdeggleston**

### CODE REVIEW

**Comment by dalaro** [comment]
Hi @bdeggleston.  Thanks!  This looks really promising.

I merged it against master and pushed the result of the merge into persistit-to-master.  I had to make a few seemingly minor configuration-related changes in the storage manager (500d10dda45e7e3f2c90760143d7183e234e3d15) to get the tests passing on my box, but I didn't have to touch the implementation internals at all.

There is one subset of this PR that aroused my curiosity.  You modified three files in titan-test.  In each file, you reordered transaction instantiation vs store instantiation.  Is this driven by a technical constraint?  Or is it meaningless?

**Comment by bdeggleston** [comment]
@dalaro 

Yes that was driven by a technical constraint. If you instantiate a tree (analogous to a titan k/v store) in a transaction, it will be unavailable to transactions opened before the tree creating transaction is committed. This was causing a bunch of problems in tests because trees were created after a transaction was opened. In titan however, k/v stores are always opened before any transactions are started.

**Comment by mbroecheler** [comment]
That makes sense. The re-ordering does not impact functional correctness
and you are right that opening a k/v store should precede opening a
transaction.

On Thu, Jun 20, 2013 at 9:30 AM, Blake Eggleston
notifications@github.comwrote:

> @dalaro https://github.com/dalaro
> 
> Yes that was driven by a technical constraint. If you instantiate a tree
> (analogous to a titan k/v store) in a transaction, it will be unavailable
> to transactions opened before the tree creating transaction is committed.
> This was causing a bunch of problems in tests because trees were created
> after a transaction was opened. In titan however, k/v stores are always
> opened before any transactions are started.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/pull/276#issuecomment-19764866
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by dalaro** [comment]
Thanks for the explanation.  For my own future reference, here's the exception I get locally when I intentionally break the ordering constraint:

```
com.persistit.exception.RollbackException
        at com.persistit.TimelyResource.addVersion(TimelyResource.java:333)
        at com.persistit.TimelyResource.addVersion(TimelyResource.java:113)
        at com.persistit.TimelyResource.getVersion(TimelyResource.java:134)
        at com.persistit.Tree.version(Tree.java:175)
        at com.persistit.Tree.setRootPageAddress(Tree.java:328)
        at com.persistit.VolumeStructure.getTree(VolumeStructure.java:216)
        at com.persistit.Volume.getTree(Volume.java:390)
        at com.persistit.Exchange.init(Exchange.java:421)
        at com.persistit.Exchange.<init>(Exchange.java:381)
        at com.persistit.Persistit.getExchange(Persistit.java:866)
        at com.persistit.Persistit.getExchange(Persistit.java:918)
        at com.thinkaurelius.titan.diskstorage.persistit.PersistitTransaction.getExchange(PersistitTransaction.java:121)
        at com.thinkaurelius.titan.diskstorage.persistit.PersistitTransaction.getExchange(PersistitTransaction.java:113)
        at com.thinkaurelius.titan.diskstorage.persistit.PersistitKeyValueStore.insert(PersistitKeyValueStore.java:316)
        at com.thinkaurelius.titan.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter.mutate(OrderedKeyValueStoreAdapter.java:74)
        ...
```

A little obtuse to the uninitiated like myself, but it's fine since Titan users don't normally touch backend instances directly.

If we wanted to catch accidental transaction/store ordering violations, then I suppose we could use an AtomicInt/Long incrementAndGet'd by store constructors, get'd by transaction constructors, and checked for store <= txn in all public store methods.  But that would be a separate issue.

I think this is good to go.  I'm planning to merge persistit-to-master into master later today.

**Pull request closed without merging**
