### PR TITLE
MapR Tables (HBase) supported as Titan Backend

### PR DESCRIPTION
**Pull request by boorad**
Here are my changes that were required to use MapR jar files.  I think they're unobtrusive, as you only use this with the 'mapr-m7' maven profile.

Also, there was a call to what I would characterize as unreliable modifyTable() in HBase.  This patch works with both MapR tables as well as Apache HBase, and is probably the solution to thinkaurelius/titan#165.

### CODE REVIEW

**Comment by dalaro** [comment]
This is great, I'm glad you set this up in a pom profile.  I have one question before merging: can we keep the `setCompressionType` call? dbc446e0c2ded75f08f4e52db786c3726576e5d0 deletes it but I'd like to keep it if MapR supports it.

**Comment by boorad** [comment]
We can keep it.  But MapR compresses naively.  LZ4 by default.  If you
like, it can stay for stock hbase.

Cheers,
BA

**Comment by dalaro** [comment]
I added an optional Compression.Algorithm override option in #584.  Leaving it unspecified lets the underlying implementation use its default (to get no compression one would have to explicitly set it to NONE).

I also merged this into titan05 with aca2ec3227ae78308ac3250fcee6f075887c8c48.  I recently split the titan-hbase module into titan-hbase-094 and -096 submodules, and I put the MapR profile in -094.

The MapR profile threw a ClassNotFoundException in testing on a ZK class when I used version 3.3.6 as specified in the PR.  When I used ZK 3.4.5 the suite passed.  Do you know what's going on there?

**Comment by dalaro** [comment]
Changed the ZK version used in the MapR build to 3.4.5 in 061e780f650e7cd8d57329879d914b44447365b6.  Please reopen if there's something I'm missing.

**Pull request closed without merging**
