### PR TITLE
Update jersey

### PR DESCRIPTION
**Pull request by ghost**
update version of jersey

### CODE REVIEW

**Comment by ghost** [comment]
Looks like the current version of jersey (1.9) is later than this pull request.  Cancelling.

**Comment by ghost** [comment]
Actually, I closed this and I should not have.  We should upgrade jersey to 1.19 per this pull request.  I have a touch of dyslexia which led me to temporarily misread the version.

**Comment by spmallette** [comment]
i haven't looked, but what is jersey used for in titan now that Rexster is gone - is there some other component that requires it?

**Comment by spmallette** [comment]
answered my own question, looks like jersey is all up in hadoop/hbase stuff.

**Comment by ghost** [comment]
But you know...when doing all of the SparkGraphComputer testing,  I ended up needing to back jersey down to 1.9 to get stuff to work.  It was like Spark was using an older version and was giving servlet class not found errors, if I recall.  So I am cancelling this particular one after doing that testing.

**Comment by spmallette** [comment]
I think this is main reason I've been a little hesitant on some of your other PRs around version bumps.  The dependencies are a pretty delicate house of cards and the test cases may not catch a big problem on what seems like an innocuous change in version.

**Pull request closed without merging**
