### PR TITLE
Guava 18 and HPPC 0.7 compatibility updates

### PR DESCRIPTION
**Pull request by nuixkeith**
We are using updated libraries for ElasticSearch which I think are on the roadmap for Titan to change over to anyway.

### CODE REVIEW

**Comment by dalaro** [comment]
What titan05 dep needs hppc 0.7?  I recently did the find-replace dance for hppc 0.7.1 compatibility in titan09 (9a49faa3669fc2c03e458c7999ecf095e0b0725d), but IIRC that was motivated by TP3's gremlin-core needing it ( #1110).

I'm also hesitant to change titan05's Guava version in a bugfix release.  We're planning to use a newer Guava (maybe 18, but at least later than 15) on titan09/1.0 as part of #854.

**Comment by nuixkeith** [comment]
Hi Dan,

These changes were to make Titan compatible with an Elastic Search project.

For the 2nd point you do not need to update the Guava version.  The bugfix
just stops Titan from using an already deprecated method so that it is
compatible if someone is using Guava 18 in their project.

I understand not wanting to change dependencies for a bugfix release.

Thanks,

Keith

On Sat, Aug 29, 2015 at 10:32 AM, Dan LaRocque notifications@github.com
wrote:

> What titan05 dep needs hppc 0.7? I recently did the find-replace dance for
> hppc 0.7.1 compatibility in titan09 (9a49faa
> https://github.com/thinkaurelius/titan/commit/9a49faa3669fc2c03e458c7999ecf095e0b0725d),
> but IIRC that was motivated by TP3's gremlin-core needing it ( #1110
> https://github.com/thinkaurelius/titan/issues/1110).
> 
> I'm also hesitant to change titan05's Guava version in a bugfix release.
> We're planning to use a newer Guava (maybe 18, but at least later than 15)
> on titan09/1.0 as part of #854
> https://github.com/thinkaurelius/titan/issues/854.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/pull/1129#issuecomment-135921220.

## 

_Keith Player | *_Principal Software Engineer *
keith@nuix.com | www.nuix.com

Ph: + 61 2 9280 0699 | Fax: +61 2 9212 6902

Level 23, 1 Market Street, Sydney NSW 2000, Australia

Twitter: twitter.com/nuix http://www.twitter.com/nuix

"No software other than Nuix can process large collections fast enough to
meet the SEC's desired timeframes"
_The US Securities and Exchange Commission_

**Comment by dalaro** [comment]
Thanks for following up.

The Guava change makes sense.  I pulled out the `createStopwatch` change on titan05 by itself and committed it as 4b6296ed4379bde7088a0135fb29262ac6f46c5d.  I didn't want to merge the PR into titan05 since it has the hppc changes baked in alongside the `createStopwatch` change.  I also found five other uses of `'new Stopwatch` in titan05 test code and converted them to `createStopwatch` in 86462068abc0a267d4d04ba61b22bbc74a09a4bd.

Bryn apparently already fixed the Guava Stopwatch compat issue on titan09 back in April.  7b3de6c84b55f869f087ae3a67379a1b54aad8a7 removed this and a few other seemingly titan09-specific `new Stopwatch` invocations in StandardIDPool.

Which ES versions require hppc 0.7?

**Comment by nuixkeith** [comment]
Hi Dan,

Sounds like we are getting a little ahead of ourselves with ES.  Our
developer working on ES integration said the following:

"Version 2.0 which is currently in beta.

Prior versions (current is 1.71 use 0.6)"

So I guess the hppc stuff isn't going to be necessary for most people just
yet.

Thanks for your assistance,

Keith

On Fri, Sep 4, 2015 at 6:21 AM, Dan LaRocque notifications@github.com
wrote:

> Thanks for following up.
> 
> The Guava change makes sense. I pulled out the createStopwatch change on
> titan05 by itself and committed it as 4b6296e
> https://github.com/thinkaurelius/titan/commit/4b6296ed4379bde7088a0135fb29262ac6f46c5d.
> I didn't want to merge the PR into titan05 since it has the hppc changes
> baked in alongside the createStopwatch change. I also found five other
> uses of 'new Stopwatch in titan05 test code and converted them to
> createStopwatch in 8646206
> https://github.com/thinkaurelius/titan/commit/86462068abc0a267d4d04ba61b22bbc74a09a4bd
> .
> 
> Bryn apparently already fixed the Guava Stopwatch compat issue on titan09
> back in April. 7b3de6c
> https://github.com/thinkaurelius/titan/commit/7b3de6c84b55f869f087ae3a67379a1b54aad8a7
> removed this and a few other seemingly titan09-specific new Stopwatch
> invocations in StandardIDPool.
> 
> Which ES versions require hppc 0.7??
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/pull/1129#issuecomment-137563194.

## 

_Keith Player | *_Principal Software Engineer *
keith@nuix.com | www.nuix.com

Ph: + 61 2 9280 0699 | Fax: +61 2 9212 6902

Level 23, 1 Market Street, Sydney NSW 2000, Australia

Twitter: twitter.com/nuix http://www.twitter.com/nuix

"No software other than Nuix can process large collections fast enough to
meet the SEC's desired timeframes"
_The US Securities and Exchange Commission_

**Comment by mbroecheler** [comment]
Sounds like this is resolved.

**Pull request closed without merging**
